packages:
  - packages/*

ignoreWorkspaceRootCheck: true
shellEmulator: true

catalogs:
  dev:
    '@antfu/eslint-config': ^5.4.1
    '@antfu/ni': ^26.1.0
    '@antfu/utils': ^9.2.1
    '@types/node': ^24.6.1
    '@typescript-eslint/parser': ^8.45.0
    '@typescript-eslint/utils': ^8.45.0
    bumpp: ^10.2.3
    eslint: ^9.36.0
    eslint-plugin-format: ^1.0.2
    eslint-vitest-rule-tester: ^2.2.2
    jiti: ^2.6.0
    lint-staged: ^16.2.3
    simple-git-hooks: ^2.13.1
    tsx: ^4.20.6
    typescript: ^5.9.3
    unbuild: ^3.6.1
    vite: ^7.1.7
  prod:
    empathic: ^2.0.0
    jsonc-eslint-parser: ^2.4.1
    pathe: ^2.0.3
    tinyglobby: ^0.2.15
    yaml: ^2.8.1
    yaml-eslint-parser: ^1.3.0
  test:
    tinyexec: ^1.0.1
    vitest: ^3.2.4
    vitest-package-exports: ^0.1.1
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
