cleanupUnusedCatalogs: true
catalogMode: prefer
trustPolicy: no-downgrade
ignoreWorkspaceRootCheck: true
shellEmulator: true

packages:
  - packages/*

catalogs:
  dev:
    '@antfu/eslint-config': ^7.0.1
    '@antfu/ni': ^28.2.0
    '@antfu/utils': ^9.3.0
    '@types/node': ^25.0.9
    '@typescript-eslint/parser': ^8.53.0
    '@typescript-eslint/utils': ^8.53.0
    '@typescript/native-preview': 7.0.0-dev.20260118.1
    bumpp: ^10.4.0
    eslint: ^9.39.2
    eslint-plugin-format: ^1.3.1
    eslint-vitest-rule-tester: ^3.0.1
    jiti: ^2.6.1
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
    tsx: ^4.21.0
    typescript: ^5.9.3
    unbuild: ^3.6.1
    vite: ^7.3.1
  prod:
    empathic: ^2.0.0
    jsonc-eslint-parser: ^2.4.2
    pathe: ^2.0.3
    tinyglobby: ^0.2.15
    yaml: ^2.8.2
    yaml-eslint-parser: ^2.0.0
  test:
    tinyexec: ^1.0.2
    vitest: ^4.0.17
    vitest-package-exports: ^1.1.2

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
