packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalogs:
  dev:
    '@antfu/eslint-config': ^5.2.0
    '@antfu/ni': ^25.0.0
    '@antfu/utils': ^9.2.0
    '@types/node': ^24.2.0
    '@typescript-eslint/parser': ^8.39.0
    '@typescript-eslint/utils': ^8.39.0
    bumpp: ^10.2.2
    eslint: ^9.32.0
    eslint-plugin-format: ^1.0.1
    eslint-vitest-rule-tester: ^2.2.1
    jiti: ^2.5.1
    lint-staged: ^16.1.4
    simple-git-hooks: ^2.13.1
    tsx: ^4.20.3
    typescript: ^5.9.2
    unbuild: ^3.6.0
    vite: ^7.1.1
  prod:
    find-up-simple: ^1.0.1
    jsonc-eslint-parser: ^2.4.0
    pathe: ^2.0.3
    tinyglobby: ^0.2.14
    yaml: ^2.8.1
    yaml-eslint-parser: ^1.3.0
  test:
    tinyexec: ^1.0.1
    vitest: ^3.2.4
    vitest-package-exports: ^0.1.1
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
