cleanupUnusedCatalogs: true
catalogMode: prefer
trustPolicy: no-downgrade
ignoreWorkspaceRootCheck: true
shellEmulator: true

packages:
  - packages/*

catalogs:
  dev:
    '@antfu/eslint-config': ^6.4.2
    '@antfu/ni': ^28.0.0
    '@antfu/utils': ^9.3.0
    '@types/node': ^24.10.1
    '@typescript-eslint/parser': ^8.48.1
    '@typescript-eslint/utils': ^8.48.1
    bumpp: ^10.3.2
    eslint: ^9.39.1
    eslint-plugin-format: ^1.1.0
    eslint-vitest-rule-tester: ^3.0.0
    jiti: ^2.6.1
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
    tsx: ^4.21.0
    typescript: ^5.9.3
    unbuild: ^3.6.1
    vite: ^7.2.7
  prod:
    empathic: ^2.0.0
    jsonc-eslint-parser: ^2.4.2
    pathe: ^2.0.3
    tinyglobby: ^0.2.15
    yaml: ^2.8.2
    yaml-eslint-parser: ^1.3.2
  test:
    tinyexec: ^1.0.2
    vitest: ^4.0.15
    vitest-package-exports: ^0.1.1

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
